name: Generate podcast feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run feed generator
        run: |
          python rss-feed.py
      - name: Push modified py file to repo
        run: |
          git config --global user.email "ugochiukaegbu19@gmail.com"
          git config --global user.name "zenitugo"
          git add .
          git commit -m 'xml script for the podcast'
          git push
