name: Generate podcast feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: run Podcast generator
        uses: zenitugo/podcast-generator@main